const { chromium } = require(process.env.BOOKANALYST_PLAYWRIGHT || 'playwright');
const fs = require('fs');
(async () => {
  const browser = await chromium.launch({ channel:'msedge', headless:true });
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const failures=[];page.on('pageerror',e=>failures.push(e.message));
  const base=process.env.BOOKANALYST_CREDENTIAL_TEST_URL || 'http://127.0.0.1:8767';
  const key='test-ui-key-'+Date.now();
  try {
    await page.goto(base,{waitUntil:'networkidle'});
    await page.locator('nav [data-nav="settings"]').click();
    await page.locator('[data-provider-select="custom_api"]').click();
    const input=page.locator('[name="custom_api_api_key"]');
    await input.waitFor();
    if(await page.locator('[name="custom_env"]').count())throw Error('Environment-name input still present');
    if(await input.getAttribute('type')!=='text')throw Error('Key is not editable text');
    await input.fill(key);
    let saved=page.waitForResponse(r=>r.url()===base+'/api/settings' && r.request().method()==='PUT');
    await page.getByRole('button',{name:'保存设置',exact:true}).click();
    let response=await saved;
    if(!response.ok() || (await response.json()).connections.custom_api.api_key!==key)throw Error('Key not returned');
    await page.waitForFunction(key=>document.querySelector('[name="custom_api_api_key"]').value===key,key);
    if(await input.inputValue()!==key)throw Error('Key not displayed');
    saved=page.waitForResponse(r=>r.url()===base+'/api/settings' && r.request().method()==='PUT');
    await page.getByRole('button',{name:'保存设置',exact:true}).click();
    response=await saved;
    if(!(await response.json()).connections.custom_api.api_key_configured)throw Error('Blank erased key');
    await page.reload({waitUntil:'networkidle'});
    await page.locator('nav [data-nav="settings"]').click();
    await page.locator('[data-provider-select="custom_api"]').click();
    await input.waitFor();
    if(await input.inputValue()!==key)throw Error('Reload lost key');
    if(await page.locator('[data-connection-field="clear_api_key"]').count())throw Error('Separate clear option remains');
    await page.screenshot({path:'.bookanalyst/credentials-settings.png',fullPage:true});
    await input.fill('');
    saved=page.waitForResponse(r=>r.url()===base+'/api/settings' && r.request().method()==='PUT');
    await page.getByRole('button',{name:'保存设置',exact:true}).click();
    response=await saved;
    if((await response.json()).connections.custom_api.api_key_configured)throw Error('Clear failed');
    if(failures.length)throw Error(failures.join('\n'));
    fs.writeFileSync('.bookanalyst/credentials-browser-report.json',JSON.stringify({plaintextInput:true,save:true,unchangedPreserves:true,reloadVisible:true,clear:true,errors:failures},null,2));
    console.log('Credential UI: plain input, save, unchanged preservation, reload display and blank clears passed.');
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
