const {chromium}=require(process.env.BOOKANALYST_PLAYWRIGHT || "playwright");
const path=require("node:path");
let activeBrowser;
(async()=>{
 const browser=await chromium.launch({channel:"msedge",headless:true});
 activeBrowser=browser;
 const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
 const errors=[];
 page.on("pageerror",e=>errors.push(e.message));
 await page.goto("http://127.0.0.1:8765",{waitUntil:"networkidle"});
 await page.getByRole("heading",{name:"书籍",exact:true}).waitFor();
 if(!await page.getByText("532 页",{exact:true}).count())throw Error("Real book not registered");
 await page.screenshot({path:"tmp/browser-library.png",fullPage:true});
 await page.getByRole("button",{name:"创建运行 →",exact:true}).click();
 const form=page.locator("#run-form");
 if(await page.locator("#run-profile").count())throw Error("Page-profile picker must not be the book entry");
 if(await form.locator('[name="profile"]').inputValue()!=="book" ||
    await form.locator('[name="start_page"]').inputValue()!=="1" ||
    await form.locator('[name="end_page"]').inputValue()!=="532")throw Error("Book entry must cover all 532 pages");
 if(await form.locator('[name="max_llm_requests"]').inputValue()!=="")throw Error("User must choose the request budget");
 await page.waitForFunction(()=>document.querySelectorAll("#models-openai_subscription option").length>0,{},{timeout:60000});
 const upstream=await page.evaluate(async()=>await (await fetch("/api/connections/openai_subscription/status")).json());
 const choices=await page.locator("#models-openai_subscription option").evaluateAll(items=>items.map(i=>i.value));
 if(JSON.stringify(choices)!==JSON.stringify(upstream.models.map(m=>m.model||m.id)))throw Error("Model choices differ from upstream");
 await page.screenshot({path:"tmp/browser-book-run.png",fullPage:true});
 await page.locator("#close-dialog").click();
 // Internal fixture mode tests the UI without submitting the book or running real inference.
 const fixture=await page.evaluate(async()=>{
   const state=await (await fetch("/api/bootstrap")).json();
   const post=async(url,body)=>{
     const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json","x-bookanalyst-token":state.token},body:JSON.stringify(body)});
     const result=await response.json();if(!response.ok)throw Error(JSON.stringify(result));return result;
   };
   const run=await post("/api/runs",{book_id:"elliptic-pde-second-order",profile:"offline_fixture",start_page:14,end_page:14});
   await post("/api/runs/"+run.id+"/start",{revision:run.revision,operation_id:crypto.randomUUID()});
   return run;
 });
 await page.reload({waitUntil:"networkidle"});
 await page.locator('[data-run="'+fixture.id+'"]').click();
 await page.getByRole("heading",{name:"内容对照",exact:true}).waitFor();
 await page.getByText("预录夹具证据",{exact:false}).waitFor({timeout:90000});
 await page.getByRole("link",{name:"导出已验收工程 ↓",exact:true}).waitFor({timeout:90000});
 if(await page.locator(".stage.PASSED").count()!==9)throw Error("Fixture did not pass all nine stages");
 if(await page.locator("#pdf-upload").isVisible())throw Error("Hidden upload input leaked into layout");
 await page.getByText("查看统一生成的 TeX 正文",{exact:false}).waitFor({timeout:90000});
 const selected=page.locator(".column:nth-child(2) .atom").nth(4);
 await selected.click();
 if(await page.locator(".region.selected").count()!==1)throw Error("Original-page source region not selected");
 if(await page.locator(".column:nth-child(3) .atom.selected").count()!==1)throw Error("TeX source not selected");
 if(await page.locator(".katex").count()<4)throw Error("Local mathematical previews missing");
 await page.locator("#compare-page").fill("15");
 await page.locator("#compare-page").dispatchEvent("change");
 await page.getByText("0 个内容块",{exact:true}).waitFor();
 await page.locator(".node-nav button").first().click();
 await page.waitForFunction(()=>document.querySelector("#compare-page").value==="14");
 await page.getByText("修正与局部重跑",{exact:true}).click();
 await page.locator("#rerun-stage").selectOption("S7");
 await page.getByRole("button",{name:"查看影响范围",exact:true}).click();
 await page.locator("#rerun-plan").getByText("S7 → S8",{exact:false}).waitFor();
 await page.getByRole("button",{name:"执行重跑",exact:true}).click();
 await page.locator(".page-head .subtitle").filter({hasText:"修订 2"}).waitFor();
 await page.getByRole("link",{name:"导出已验收工程 ↓",exact:true}).waitFor({timeout:90000});
 if(await page.locator(".stage.PASSED").count()!==9)throw Error("Compile rerun did not pass all gates");
 await page.getByText("修正与局部重跑",{exact:true}).click();
 await page.locator(".column:nth-child(2) .atom").nth(4).click();
 const layout=await page.evaluate(()=>({height:document.documentElement.scrollHeight,mainBottom:document.querySelector("#main").getBoundingClientRect().bottom+scrollY}));
 console.log("Layout",JSON.stringify(layout));
 await page.screenshot({path:"tmp/browser-compare.png",fullPage:true});
 await page.getByRole("button",{name:"设置",exact:false}).first().click();
 await page.getByRole("heading",{name:"设置",exact:true}).waitFor();
 await page.getByRole("heading",{name:"ChatGPT 官方订阅"}).waitFor();
 await page.getByRole("button",{name:"保存设置",exact:true}).click();
 await page.getByText("设置已保存",{exact:true}).waitFor();
 await page.screenshot({path:"tmp/browser-settings.png",fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.getByRole("button",{name:"书籍",exact:false}).first().click();
 await page.getByRole("heading",{name:"书籍",exact:true}).waitFor();
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+2);
 if(overflow)throw Error("Mobile viewport has horizontal overflow");
 await page.screenshot({path:"tmp/browser-mobile.png",fullPage:true});
 if(errors.length)throw Error(errors.join("\n"));
 await browser.close();
 console.log("Browser checks passed: real book, fixture run, source linking, local math, settings, mobile layout.");
})().catch(async error=>{console.error(error);await activeBrowser?.close();process.exitCode=1;});
